apiVersion: v1
kind: Service
metadata:
  name: mix-fast
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  selector:
    app: mix-fast
  ports:
  - name: "9080"
    port: 9080
    targetPort: 9080
    nodePort: 30000
  type: LoadBalancer