version: '3.5'

services:
  mysql:
    image: mysql:latest
    hostname: mysql-mixfast
    environment:
      MYSQL_DATABASE: 'dbmixfast'
      MYSQL_USER: 'mixfast'
      MYSQL_PASSWORD: 'q1w2e3r4'
      MYSQL_ROOT_PASSWORD: 'q1w2e3r4'
    ports:
      - '3308:3306'
    expose:
      - '3308'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - fiap

  mixfast:
    image: mcapucho/mixfast:1.0.0
    hostname: app-mixfast
    platform: linux/amd64
    environment:
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: 'q1w2e3r4'
      MYSQL_SCHEMA: 'dbmixfast'
      MYSQL_USER: 'mixfast'
      MYSQL_PORT: '3306'
    ports:
      - '9080:9080'
    expose:
      - '9080'
    networks:
      - fiap
    depends_on:
      - mysql

volumes:
  my-db:

networks:
  fiap:
    driver: bridge