version: '3.5'

services:
  mysql:
    image: mysql:latest
    hostname: mysql-mixfast
    environment:
      MYSQL_DATABASE: 'dbmixfast'
      MYSQL_USER: 'mixfast'
      MYSQL_PASSWORD: 'q1w2e3r4'
      MYSQL_ROOT_PASSWORD: 'q1w2e3r4'
    ports:
      - '3308:3306'
    expose:
      - '3308'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - fiap

  mixfast:
    image: mcapucho/mixfast:2.0.0
    hostname: app-mixfast
    environment:
      DB_HOST: mysql
      DB_PASSWORD: 'q1w2e3r4'
      DB_SCHEMA: 'dbmixfast'
      DB_USER: 'mixfast'
      DB_PORT: '3306'
      MERCADO_PAGO_TOKEN: 'TEST-2380996068417028-090223-5c491b74d2c2d766d02bbe8269ac4fe3-1398154307'
      MERCADO_PAGO_USER_ID: '1398154307'
      MERCADO_PAGO_POS: 'MIXFASTCX01'
    ports:
      - '9080:9080'
    expose:
      - '9080'
    networks:
      - fiap
    depends_on:
      - mysql

volumes:
  my-db:

networks:
  fiap:
    driver: bridge