spring:
  application:
    name: mix-fast
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_SCHEMA}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

feign:
  client:
    config:
      url: https://api.mercadopago.com/instore/orders/qr/seller/collectors/1398731230/pos/MIXFAST001/qrs
      token: TEST-1659689448850865-061320-4eabc1f0b8b9802cc2b463a1f42249ce-1398731230

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-mix-fast.html

server:
  port: 9080