apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  ports:
  - port: 3308
    protocol: TCP
    targetPort: 3306
    nodePort: 30001
  selector:
    app: mysql
  type: NodePort