apiVersion: v1
kind: Service
metadata:
  name: mixfast-backend
spec:
  selector:
    app: mixfast
    tier: backend
  ports:
    - protocol: "TCP"
      port: 9080
      nodePort: 30000
  type: LoadBalancer
